### ISSUE TITLE
Strong name?

### ISSUE THREAD

**Issue by josephnarai** [AvaloniaCommunity/awesome-avalonia#48]
I have an EV certificate and when I attempt to sign the assembly for my Avalonia based app (I'm just trying to sign a simple Button Test app), I get the following error:

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "CompileAvaloniaXamlTask" task failed unexpectedly.
System.Security.Cryptography.CryptographicException: Unknown blob format.
   at Mono.Security.Cryptography.CryptoConvert.FromCapiKeyBlob(Byte[] blob, Int32 offset)
   at Mono.Cecil.Mixin.CreateRSA(WriterParameters writer_parameters)
   at Mono.Cecil.CryptoService.GetPublicKey(WriterParameters parameters)
   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
   at Avalonia.Build.Tasks.XamlCompilerTaskExecutor.Compile(IBuildEngine engine, String input, String[] references, String projectDirectory, String output, Boolean verifyIl, MessageImportance logImportance, String strongNameKey, Boolean patchCom, Boolean skipXamlCompilation)
   at Avalonia.Build.Tasks.CompileAvaloniaXamlTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	AvaloniaButtonTest	C:\Users\Joe\.nuget\packages\avalonia\0.10.8\buildTransitive\AvaloniaBuildTasks.targets	96	

   If I sign a non-Avalonia project it signs ok, so I assume (although by no means am sure), that the issue is in Avalonia. Has anyone tried creating a strong named assembly?

   I'm new to signing, so if there is an alternative to the way I'm signing it, please point me in the right direction! It's very confusing!

Thanks

**Comment by OmidID** [comment]
@josephnarai I think you ask your question in the wrong place.
If your question is related to Avalonia you could ask in the Avalonia repository : https://github.com/AvaloniaUI/Avalonia

**Comment by josephnarai** [comment]
Apologies.
